/**
 * Generate a SQL seed file for the `songs` table from the two DDR CSV exports.
 *
 * It maps CSV headers to columns using the same normalization as the schema
 * (lowercase, brackets removed, symbols -> underscore, trimmed), keeps only the
 * columns currently defined in db/schema.ts, and writes batched multi-row
 * INSERTs to db/seed.sql.
 *
 * Run:    npx tsx db/seed.ts
 * Apply:  npx wrangler d1 execute ddr-trace-db --local --file=db/seed.sql
 *         (swap --local for --remote to seed the remote D1)
 */
import { createReadStream, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import path from "node:path";
import { parseCsvLine, toColumnName } from "./csv-utils";

const DATA_DIR = path.join(__dirname, "data");
const OUT_FILE = path.join(__dirname, "seed.sql");
const ROWS_PER_INSERT = 500;

const FILES: { file: string; type: "single" | "double" }[] = [
    { file: "DanceDanceRevolution Chart Data Spreadsheet - Single.csv", type: "single" },
    { file: "DanceDanceRevolution Chart Data Spreadsheet - Double.csv", type: "double" },
];

type Kind = "text" | "integer";

// Target columns (excluding id + type), in insert order. `col` is the DB column
// name AND the normalized form of the CSV header used to locate the source value.
const COLUMNS: { col: string; kind: Kind }[] = [
    { col: "folder", kind: "text" },
    { col: "title", kind: "text" },
    { col: "difficulty", kind: "text" },
    { col: "rating", kind: "integer" },
    { col: "song_length", kind: "integer" },
    { col: "display_bpm_min", kind: "integer" },
    { col: "display_bpm_max", kind: "integer" },
    { col: "bpm_changes", kind: "integer" },
    { col: "artist", kind: "text" },
    { col: "notes", kind: "integer" },
    { col: "steps", kind: "integer" },
    { col: "jumps", kind: "integer" },
    { col: "holds", kind: "integer" },
    { col: "shock_arrows", kind: "integer" },
    { col: "max_combo_steps_shock_arrows", kind: "integer" },
];

function sqlText(v: string): string {
    return "'" + v.replace(/'/g, "''") + "'";
}

function sqlInt(v: string): string {
    const t = v.trim();
    if (t === "" || t === "N/A") return "NULL";
    const n = Number(t);
    return Number.isFinite(n) ? String(Math.round(n)) : "NULL";
}

/** Build "(...)" value tuples for one CSV file. */
async function rowsForFile(
    file: string,
    type: "single" | "double",
): Promise<{ tuples: string[]; skipped: number }> {
    const rl = createInterface({
        input: createReadStream(path.join(DATA_DIR, file)),
        crlfDelay: Infinity,
    });

    let colIndex: Record<string, number> = {};
    const tuples: string[] = [];
    let skipped = 0;
    let isHeader = true;

    for await (const line of rl) {
        const cells = parseCsvLine(line);
        if (isHeader) {
            cells.forEach((h, i) => (colIndex[toColumnName(h)] = i));
            const missing = COLUMNS.filter((c) => !(c.col in colIndex)).map((c) => c.col);
            if (missing.length) {
                throw new Error(`${file}: missing expected columns: ${missing.join(", ")}`);
            }
            isHeader = false;
            continue;
        }
        if (cells.length <= 1 && (cells[0] ?? "").trim() === "") continue; // blank line

        const values = [sqlText(type)];
        let hasNull = false;
        for (const c of COLUMNS) {
            const raw = cells[colIndex[c.col]] ?? "";
            const v = c.kind === "integer" ? sqlInt(raw) : sqlText(raw);
            if (v === "NULL") hasNull = true; // would violate a NOT NULL column
            values.push(v);
        }
        // Every target column is NOT NULL; skip rows with missing required temp
        // (e.g. "unused" charts that have no rating).
        if (hasNull) {
            skipped++;
            continue;
        }
        tuples.push(`(${values.join(",")})`);
    }
    rl.close();
    return { tuples, skipped };
}

function chunk<T>(arr: T[], size: number): T[][] {
    const out: T[][] = [];
    for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
    return out;
}

async function main() {
    const columnList = ["type", ...COLUMNS.map((c) => c.col)].join(", ");
    const out: string[] = [
        "-- Auto-generated by db/seed.ts. Do not edit by hand.",
        "PRAGMA foreign_keys=OFF;",
        "DELETE FROM songs;",
        "",
    ];

    let total = 0;
    let totalSkipped = 0;
    for (const { file, type } of FILES) {
        const { tuples, skipped } = await rowsForFile(file, type);
        total += tuples.length;
        totalSkipped += skipped;
        out.push(`-- ${type}: ${tuples.length} rows (${skipped} skipped, missing required data)`);
        for (const batch of chunk(tuples, ROWS_PER_INSERT)) {
            out.push(`INSERT INTO songs (${columnList}) VALUES`);
            out.push(batch.join(",\n") + ";");
        }
        out.push("");
    }

    writeFileSync(OUT_FILE, out.join("\n"));
    console.log(
        `Wrote ${total} rows to ${path.relative(process.cwd(), OUT_FILE)} (${totalSkipped} skipped, missing required data)`,
    );
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
